server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/